server:
  port: 8888
  servlet:
    context-path: /
spring:
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tomato?serverTimezone=Asia/Shanghai
    username: tomato@123
    password: tomato@123
  thymeleaf:
    cache: false
    enabled: true
    mode: LEGACYHTML5
    suffix: .html
